//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.Application.Messages {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessagesValidationsCliente {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessagesValidationsCliente() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cliente.Application.Messages.MessagesValidationsCliente", typeof(MessagesValidationsCliente).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se permite el ingreso de caracteres especiales..
        /// </summary>
        internal static string ValidationsCalienteCaracteresEspeciales {
            get {
                return ResourceManager.GetString("ValidationsCalienteCaracteresEspeciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Apellido permite maximo 15 caracteres.
        /// </summary>
        internal static string ValidationsClienteApellidoMax15Caracteres {
            get {
                return ResourceManager.GetString("ValidationsClienteApellidoMax15Caracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Apellido no puede ser nulo.
        /// </summary>
        internal static string ValidationsClienteApellidoNotNull {
            get {
                return ResourceManager.GetString("ValidationsClienteApellidoNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo edad debe ser menor a 100.
        /// </summary>
        internal static string ValidationsClienteEdadMenor100 {
            get {
                return ResourceManager.GetString("ValidationsClienteEdadMenor100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo EMail posee un formato incorrecto.
        /// </summary>
        internal static string ValidationsClienteEMailFormatoIncorrecto {
            get {
                return ResourceManager.GetString("ValidationsClienteEMailFormatoIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo EMail permite maximo 25 caracteres.
        /// </summary>
        internal static string ValidationsClienteEMailMax25Caracteres {
            get {
                return ResourceManager.GetString("ValidationsClienteEMailMax25Caracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo EMail no puede ser nulo.
        /// </summary>
        internal static string ValidationsClienteEMailNotNull {
            get {
                return ResourceManager.GetString("ValidationsClienteEMailNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Nombre debe ser distinto al campo Apellido.
        /// </summary>
        internal static string ValidationsClienteNombreIgualApellido {
            get {
                return ResourceManager.GetString("ValidationsClienteNombreIgualApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Nombre permite maximo 15 caracteres.
        /// </summary>
        internal static string ValidationsClienteNombreMax15Caracteres {
            get {
                return ResourceManager.GetString("ValidationsClienteNombreMax15Caracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo Nombre no puede ser nulo.
        /// </summary>
        internal static string ValidationsClienteNombreNotNull {
            get {
                return ResourceManager.GetString("ValidationsClienteNombreNotNull", resourceCulture);
            }
        }
    }
}
